### ISSUE TITLE
IP is leaked briefly when starting a download 

### ISSUE THREAD

**Issue by arod0719** [master-hax/compose-wireguard-deluge#2]
I noticed that after following your configuration, my public IP is leaked briefly before properly connecting to the wireguard conf. This can be tracked using this website: https://www.whatismyip.net/tools/torrent-ip-checker/ and seems to be reproducible anytime I begin a download. Any suggestions? 

![ipleak](https://user-images.githubusercontent.com/50396589/222791498-66fbdc44-8cd5-4345-9a75-db86e69b3489.PNG)

My compose when getting this issue is:
```
version: "3.7"
services:

  torrent-client:
    image: linuxserver/deluge
    restart: unless-stopped
    network_mode: service:vpn-sidecar
    depends_on:
      - vpn-sidecar
    volumes:
      - deluge-data-volume:/config
      - downloads-volume:/downloads

  web-proxy:
    image: dperson/nginx
    restart: unless-stopped
    networks:
      - default
      - isolated_torrent_network
    environment:
      - PROXY=http://torrent-client:8112;/
    ports:
      - 8112:80
    links:
      - vpn-sidecar:torrent-client
    depends_on:
      - torrent-client
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx

  vpn-sidecar:
    image: linuxserver/wireguard
    restart: unless-stopped
    networks:
      - isolated_torrent_network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules
      - wgclient-data-volume:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0 # for raspberry pi compatibility?

volumes:
  deluge-data-volume: # deluge application files - change to a persistent location
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/config/"
  downloads-volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/downloads/"
  wgclient-data-volume: 
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/wireguard/" 

networks:
  default:
  isolated_torrent_network:

```
